openapi: 3.0.0
info:
  version: 1.0.0
  title: PICKPL's API docs
  description: PICKPL's SERVER SEMINAR
  license:
    name: "Yuhyeon, Yeri, Seungtaek"
servers:
  - url: "http://localhost:3000/"
components:
  parameters: null
  #Schemas : model 정보
  schemas:
    user:
      properties:
        _id:
          type: string
          description: 오브젝트 아이디
        nickname:
          type: string
          description: 닉네임
        email:
          type: string
          description: 이메일 주소
        success_rate_uploaded_songs:
          type: number
          description: 노래 등록 성공률
        accepted_playlists:
          type: Playlist
          description: 수락된 플레이리스트
        rejected_playlists:
          type: Playlist
          description: 거절된 플레이리스트
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  #Examples
  examples:
    userExample:
      value:
        {
          "_id": "6283a755c2f673e5e81a6fea",
          "email": "validateTest-email2@naver.com",
          "nickname": "홍길동",
          "success_rate_uploaded_songs": "3499",
          "accepted_playlists": "6283a755c2f673e5e81a6fea",
          "rejected_playlists": "6283a755c2f673e5e81a6fea",
        }
  #Responses 재사용되는 애들
  responses:
    successResponse:
      description: successful request with no data
      content:
        application/json:
          schema:
            type: object
            example: { "status": 200, "success": true, "message": "message" }
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            success: false
            message: 서버 내부 오류
#Paths api 경로 지정
paths:
  /user/{userId}:
    $ref: "./user.yaml#/~1user~1{userId}"
  /user/signup:
    $ref: "./user.yaml#/~1user~1signup"
  /user/login:
    $ref: "./user.yaml#/~1user~1login"
  /user/password:
    $ref: "./user.yaml#/~1user~1password"
  /user/logout:
    $ref: "./user.yaml#/~1user~1logout"
